export const recipes = [
  {
    name: "Chiseled Obsidian",
    type: "crafting",
    ingredients: [
      { name: "Cobbled Obsidian Slab", position: 1 },
      { name: "Cobbled Obsidian Slab", position: 4 },
    ],
    result: { name: "Chiseled Obsidian", count: 1 },
  },
  {
    name: "Chiseled Obsidian",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Chiseled Obsidian", count: 1 },
  },
  {
    name: "Cobbled Obsidian",
    type: "crafting",
    ingredients: [
      { name: "Obsidian Dust", position: 0 },
      { name: "Obsidian Dust", position: 1 },
      { name: "Obsidian Dust", position: 2 },
      { name: "Obsidian Dust", position: 3 },
      { name: "Obsidian Dust", position: 4 },
      { name: "Obsidian Dust", position: 5 },
      { name: "Obsidian Dust", position: 6 },
      { name: "Obsidian Dust", position: 7 },
      { name: "Obsidian Dust", position: 8 },
    ],
    result: { name: "Cobbled Obsidian", count: 1 },
  },
  {
    name: "Cobbled Obsidian Slab",
    type: "crafting",
    ingredients: [
      { name: "Cobbled Obsidian", position: 0 },
      { name: "Cobbled Obsidian", position: 1 },
      { name: "Cobbled Obsidian", position: 2 },
    ],
    result: { name: "Cobbled Obsidian Slab", count: 6 },
  },
  {
    name: "Cobbled Obsidian Slab",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Cobbled Obsidian Slab", count: 2 },
  },
  {
    name: "Cobbled Obsidian Stairs",
    type: "crafting",
    ingredients: [
      { name: "Cobbled Obsidian", position: 0 },
      { name: "Cobbled Obsidian", position: 3 },
      { name: "Cobbled Obsidian", position: 4 },
      { name: "Cobbled Obsidian", position: 6 },
      { name: "Cobbled Obsidian", position: 7 },
      { name: "Cobbled Obsidian", position: 8 },
    ],
    result: { name: "Cobbled Obsidian Stairs", count: 4 },
  },
  {
    name: "Cobbled Obsidian Stairs",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Cobbled Obsidian Stairs", count: 1 },
  },
  {
    name: "Cobbled Obsidian Wall",
    type: "crafting",
    ingredients: [
      { name: "Cobbled Obsidian", position: 0 },
      { name: "Cobbled Obsidian", position: 1 },
      { name: "Cobbled Obsidian", position: 2 },
      { name: "Cobbled Obsidian", position: 3 },
      { name: "Cobbled Obsidian", position: 4 },
      { name: "Cobbled Obsidian", position: 5 },
    ],
    result: { name: "Cobbled Obsidian Wall", count: 6 },
  },
  {
    name: "Cobbled Obsidian Wall",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Cobbled Obsidian Wall", count: 1 },
  },
  {
    name: "Cracked Obsidian Bricks",
    type: "crafting",
    ingredients: [
      { name: "Obsidian Bricks", position: 0 },
      { name: "Obsidian Bricks", position: 1 },
      { name: "Obsidian Bricks", position: 3 },
      { name: "Obsidian Bricks", position: 4 },
    ],
    result: { name: "Cracked Obsidian Bricks", count: 4 },
  },
  {
    name: "Cracked Obsidian Bricks",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Cracked Obsidian Bricks", count: 1 },
  },
  {
    name: "Cracked Obsidian Bricks",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Bricks", position: 0 }],
    result: { name: "Cracked Obsidian Bricks", count: 1 },
  },
  {
    name: "Cracked Obsidian Bricks",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Cracked Obsidian Bricks", count: 1 },
  },
  {
    name: "Cracked Obsidian Tiles",
    type: "crafting",
    ingredients: [
      { name: "Obsidian Tiles", position: 0 },
      { name: "Obsidian Tiles", position: 1 },
      { name: "Obsidian Tiles", position: 3 },
      { name: "Obsidian Tiles", position: 4 },
    ],
    result: { name: "Cracked Obsidian Tiles", count: 4 },
  },
  {
    name: "Cracked Obsidian Tiles",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Cracked Obsidian Tiles", count: 1 },
  },
  {
    name: "Cracked Obsidian Tiles",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Bricks", position: 0 }],
    result: { name: "Cracked Obsidian Tiles", count: 1 },
  },
  {
    name: "Cracked Obsidian Tiles",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Tiles", position: 0 }],
    result: { name: "Cracked Obsidian Tiles", count: 1 },
  },
  {
    name: "Cracked Obsidian Tiles",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Cracked Obsidian Tiles", count: 1 },
  },
  {
    name: "Obsidian Brick Slab",
    type: "crafting",
    ingredients: [
      { name: "Obsidian Bricks", position: 0 },
      { name: "Obsidian Bricks", position: 1 },
      { name: "Obsidian Bricks", position: 2 },
    ],
    result: { name: "Obsidian Brick Slab", count: 6 },
  },
  {
    name: "Obsidian Brick Slab",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Obsidian Brick Slab", count: 2 },
  },
  {
    name: "Obsidian Brick Slab",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Bricks", position: 0 }],
    result: { name: "Obsidian Brick Slab", count: 2 },
  },
  {
    name: "Obsidian Brick Slab",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Obsidian Brick Slab", count: 2 },
  },
  {
    name: "Obsidian Brick Stairs",
    type: "crafting",
    ingredients: [
      { name: "Obsidian Bricks", position: 0 },
      { name: "Obsidian Bricks", position: 3 },
      { name: "Obsidian Bricks", position: 4 },
      { name: "Obsidian Bricks", position: 6 },
      { name: "Obsidian Bricks", position: 7 },
      { name: "Obsidian Bricks", position: 8 },
    ],
    result: { name: "Obsidian Brick Stairs", count: 4 },
  },
  {
    name: "Obsidian Brick Stairs",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Obsidian Brick Stairs", count: 1 },
  },
  {
    name: "Obsidian Brick Stairs",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Bricks", position: 0 }],
    result: { name: "Obsidian Brick Stairs", count: 1 },
  },
  {
    name: "Obsidian Brick Stairs",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Obsidian Brick Stairs", count: 1 },
  },
  {
    name: "Obsidian Brick Wall",
    type: "crafting",
    ingredients: [
      { name: "Obsidian Bricks", position: 0 },
      { name: "Obsidian Bricks", position: 1 },
      { name: "Obsidian Bricks", position: 2 },
      { name: "Obsidian Bricks", position: 3 },
      { name: "Obsidian Bricks", position: 4 },
      { name: "Obsidian Bricks", position: 5 },
    ],
    result: { name: "Obsidian Brick Wall", count: 6 },
  },
  {
    name: "Obsidian Brick Wall",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Obsidian Brick Wall", count: 1 },
  },
  {
    name: "Obsidian Brick Wall",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Bricks", position: 0 }],
    result: { name: "Obsidian Brick Wall", count: 1 },
  },
  {
    name: "Obsidian Brick Wall",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Obsidian Brick Wall", count: 1 },
  },
  {
    name: "Obsidian Bricks",
    type: "crafting",
    ingredients: [
      { name: "Polished Obsidian", position: 0 },
      { name: "Polished Obsidian", position: 1 },
      { name: "Polished Obsidian", position: 3 },
      { name: "Polished Obsidian", position: 4 },
    ],
    result: { name: "Obsidian Bricks", count: 4 },
  },
  {
    name: "Obsidian Bricks",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Obsidian Bricks", count: 1 },
  },
  {
    name: "Obsidian Bricks",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Obsidian Bricks", count: 1 },
  },
  {
    name: "Obsidian Dust",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian", position: 0 }],
    result: { name: "Obsidian Dust", count: 9 },
  },
  {
    name: "Obsidian",
    type: "blasting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Obsidian", count: 1 }, // Assuming count 1 if not specified for blasting/smelting
  },
  {
    name: "Obsidian",
    type: "smelting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Obsidian", count: 1 }, // Assuming count 1 if not specified for blasting/smelting
  },
  {
    name: "Obsidian Tile Slab",
    type: "crafting",
    ingredients: [
      { name: "Obsidian Tiles", position: 0 },
      { name: "Obsidian Tiles", position: 1 },
      { name: "Obsidian Tiles", position: 2 },
    ],
    result: { name: "Obsidian Tile Slab", count: 6 },
  },
  {
    name: "Obsidian Tile Slab",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Obsidian Tile Slab", count: 2 },
  },
  {
    name: "Obsidian Tile Slab",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Bricks", position: 0 }],
    result: { name: "Obsidian Tile Slab", count: 2 },
  },
  {
    name: "Obsidian Tile Slab",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Tiles", position: 0 }],
    result: { name: "Obsidian Tile Slab", count: 2 },
  },
  {
    name: "Obsidian Tile Slab",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Obsidian Tile Slab", count: 2 },
  },
  {
    name: "Obsidian Tile Stairs",
    type: "crafting",
    ingredients: [
      { name: "Obsidian Tiles", position: 0 },
      { name: "Obsidian Tiles", position: 3 },
      { name: "Obsidian Tiles", position: 4 },
      { name: "Obsidian Tiles", position: 6 },
      { name: "Obsidian Tiles", position: 7 },
      { name: "Obsidian Tiles", position: 8 },
    ],
    result: { name: "Obsidian Tile Stairs", count: 4 },
  },
  {
    name: "Obsidian Tile Stairs",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Obsidian Tile Stairs", count: 1 },
  },
  {
    name: "Obsidian Tile Stairs",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Bricks", position: 0 }],
    result: { name: "Obsidian Tile Stairs", count: 1 },
  },
  {
    name: "Obsidian Tile Stairs",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Tiles", position: 0 }],
    result: { name: "Obsidian Tile Stairs", count: 1 },
  },
  {
    name: "Obsidian Tile Stairs",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Obsidian Tile Stairs", count: 1 },
  },
  {
    name: "Obsidian Tile Wall",
    type: "crafting",
    ingredients: [
      { name: "Obsidian Tiles", position: 0 },
      { name: "Obsidian Tiles", position: 1 },
      { name: "Obsidian Tiles", position: 2 },
      { name: "Obsidian Tiles", position: 3 },
      { name: "Obsidian Tiles", position: 4 },
      { name: "Obsidian Tiles", position: 5 },
    ],
    result: { name: "Obsidian Tile Wall", count: 6 },
  },
  {
    name: "Obsidian Tile Wall",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Obsidian Tile Wall", count: 1 },
  },
  {
    name: "Obsidian Tile Wall",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Bricks", position: 0 }],
    result: { name: "Obsidian Tile Wall", count: 1 },
  },
  {
    name: "Obsidian Tile Wall",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Tiles", position: 0 }],
    result: { name: "Obsidian Tile Wall", count: 1 },
  },
  {
    name: "Obsidian Tile Wall",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Obsidian Tile Wall", count: 1 },
  },
  {
    name: "Obsidian Tiles",
    type: "crafting",
    ingredients: [
      { name: "Obsidian Bricks", position: 0 },
      { name: "Obsidian Bricks", position: 1 },
      { name: "Obsidian Bricks", position: 3 },
      { name: "Obsidian Bricks", position: 4 },
    ],
    result: { name: "Obsidian Tiles", count: 4 },
  },
  {
    name: "Obsidian Tiles",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Obsidian Tiles", count: 1 },
  },
  {
    name: "Obsidian Tiles",
    type: "stonecutting",
    ingredients: [{ name: "Obsidian Bricks", position: 0 }],
    result: { name: "Obsidian Tiles", count: 1 },
  },
  {
    name: "Obsidian Tiles",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Obsidian Tiles", count: 1 },
  },
  {
    name: "Polished Obsidian",
    type: "crafting",
    ingredients: [
      { name: "Cobbled Obsidian", position: 0 },
      { name: "Cobbled Obsidian", position: 1 },
      { name: "Cobbled Obsidian", position: 3 },
      { name: "Cobbled Obsidian", position: 4 },
    ],
    result: { name: "Polished Obsidian", count: 4 },
  },
  {
    name: "Polished Obsidian",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Polished Obsidian", count: 1 },
  },
  {
    name: "Polished Obsidian Slab",
    type: "crafting",
    ingredients: [
      { name: "Polished Obsidian", position: 0 },
      { name: "Polished Obsidian", position: 1 },
      { name: "Polished Obsidian", position: 2 },
    ],
    result: { name: "Polished Obsidian Slab", count: 6 },
  },
  {
    name: "Polished Obsidian Slab",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Polished Obsidian Slab", count: 2 },
  },
  {
    name: "Polished Obsidian Slab",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Polished Obsidian Slab", count: 2 },
  },
  {
    name: "Polished Obsidian Stairs",
    type: "crafting",
    ingredients: [
      { name: "Polished Obsidian", position: 0 },
      { name: "Polished Obsidian", position: 3 },
      { name: "Polished Obsidian", position: 4 },
      { name: "Polished Obsidian", position: 6 },
      { name: "Polished Obsidian", position: 7 },
      { name: "Polished Obsidian", position: 8 },
    ],
    result: { name: "Polished Obsidian Stairs", count: 4 },
  },
  {
    name: "Polished Obsidian Stairs",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Polished Obsidian Stairs", count: 1 },
  },
  {
    name: "Polished Obsidian Stairs",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Polished Obsidian Stairs", count: 1 },
  },
  {
    name: "Polished Obsidian Wall",
    type: "crafting",
    ingredients: [
      { name: "Polished Obsidian", position: 0 },
      { name: "Polished Obsidian", position: 1 },
      { name: "Polished Obsidian", position: 2 },
      { name: "Polished Obsidian", position: 3 },
      { name: "Polished Obsidian", position: 4 },
      { name: "Polished Obsidian", position: 5 },
    ],
    result: { name: "Polished Obsidian Wall", count: 6 },
  },
  {
    name: "Polished Obsidian Wall",
    type: "stonecutting",
    ingredients: [{ name: "Cobbled Obsidian", position: 0 }],
    result: { name: "Polished Obsidian Wall", count: 1 },
  },
  {
    name: "Polished Obsidian Wall",
    type: "stonecutting",
    ingredients: [{ name: "Polished Obsidian", position: 0 }],
    result: { name: "Polished Obsidian Wall", count: 1 },
  },
];
